# @name create
POST http://localhost:3000/game
Content-Type: application/json

{
  "name": "{{$guid}}"
}

# {
#     "data": {
#         "type": "monitors",
#         "attributes": {
#             "name": "{{$guid}}"
#         }
#     }
# }

###