# @name create
POST http://localhost:3000/game
Content-Type: application/vnd.api+json

{
    "data": {
        "type": "game",
        "attributes": {
            "name": "{{$guid}}",
            "type": "vtm"
        }
    }
}

###