
@gameId = 0be09611-1e65-44f8-a103-883cfaccf1aa
@worldId = 56e64eee-ab55-4ce1-a255-1b8b20ac78cb
@locationId = a709b873-2224-4f2a-9fc4-32b8f883c752

# @name create_game

POST http://localhost:3000/games
Content-Type: application/vnd.api+json

{
    "data": {
        "type": "games",
        "attributes": {
            "gameId": "{{gameId}}",
            "name": "Milwaukee By Night",
            "type": "vtm"
        }
    }
}

###


# @name create_world
POST http://localhost:3000/games/{{gameId}}/worlds
Content-Type: application/vnd.api+json

{
    "data": {
        "type": "worlds",
        "attributes": {
            "worldId": "{{worldId}}",
            "gameId": "{{gameId}}",
            "name": "My World"
        }
    }
}

###

# @name get_world
GET http://localhost:3000/games/{{gameId}}/worlds/{{worldId}}
Content-Type: application/vnd.api+json

###

# @name list
GET http://localhost:3000/games
Content-Type: application/vnd.api+json

###

# @name create_location
POST http://localhost:3000/games/{{gameId}}/worlds/{{worldId}}/locations
Content-Type: application/vnd.api+json

{
    "data": {
        "type": "locations",
        "attributes": {
            "locationId": "{{locationId}}",
            "gameId": "{{gameId}}",
            "worldId": "{{worldId}}",
            "name": "My Location",
            "type": "City"
        }
    }
}

###