// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID     int64
	GameID pgtype.UUID
	Name   string
	Type   string
}

type Location struct {
	Ud         int64
	LocationID pgtype.UUID
	WorldID    int64
	Type       string
	Name       string
	Path       pgtype.Text
}

type World struct {
	ID      int64
	WorldID pgtype.UUID
	GameID  int64
}
