// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID     int64
	GameID uuid.UUID
	Name   string
	Type   string
}

type Location struct {
	ID         int64
	LocationID uuid.UUID
	WorldID    int64
	Type       string
	Name       string
	Path       pgtype.Text
}

type World struct {
	ID      int64
	WorldID uuid.UUID
	GameID  int64
	Name    string
}
